---
- include: debian.yml
  when: ansible_os_family == 'Debian'

- include: popos.yml
  when: ansible_distribution == 'Pop!_OS'

- include: Fedora.yml
  when: ansible_distribution == 'Fedora'

- name: Set a hostname
  hostname:
    name: '{{ hostname }}'
    use: systemd

