- hosts: localhost
  become: yes
  roles:
    - roles/tools-role
    - roles/enpass-role
    - roles/containers-tools-role
    - roles/virt-tools-role
  vars:
    slack_url: #
    hostname: << HOSTNAME >>

- hosts: localhost
  roles:
    - roles/misc-tools-role
  vars: 
    python_pyenv_version: 3.8.6
    go_goenv_version: 1.16
    node_nvm_version: latest
