---
- name: Install the spotify flatpak
  flatpak:
    name:  https://dl.flathub.org/repo/appstream/com.spotify.Client.flatpakref
    state: present
    method: user

- name: Install Goenv
  git:
    repo: https://github.com/syndbg/goenv.git
    dest: "{{ ansible_user_dir }}/.goenv"
    
- name: Install zgen
  git:
    repo: https://github.com/tarjoilija/zgen.git
    dest: "{{ ansible_user_dir }}/.zgen"

- name: nvm
  shell: >
    curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.36.0/install.sh | bash
  args:
    creates: "{{ ansible_env.HOME }}/.nvm/nvm.sh"

- name: Dependecies Pyenv
  dnf:
    name: "{{ item }}"
    state: latest
  with_items:
  - '@Development tools'
  - zlib-devel
  - bzip2
  - bzip2-devel 
  - readline-devel
  - sqlite
  - sqlite-devel
  - openssl-devel 
  - xz 
  - xz-devel
  - libffi-devel 
  - findutils
  become: yes

- name: pyenv
  shell: >
    curl https://pyenv.run | bash