- name: Install the spotify flatpak
  flatpak:
    name:  https://dl.flathub.org/repo/appstream/com.spotify.Client.flatpakref
    state: present
    method: user

- name: Install Goenv
  git:
    repo: https://github.com/syndbg/goenv.git
    dest: "{{ ansible_user_dir }}/.goenv"
    
- name: install tlp
  apt:
    name: tlp
    state: latest
  become: yes

- name: nvm
  shell: >
    curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.36.0/install.sh | bash
  args:
    creates: "{{ ansible_env.HOME }}/.nvm/nvm.sh"

- name: install snap
  apt: 
    name: snapd
    state: latest
  become: yes

- name: enable service snapd and ensure it is not masked
  systemd:
    name: snapd
    enabled: yes
    masked: no

- name: Install authy
  snap:
    name: authy
    channel: latest/beta
  become: yes

- name: Dependecies Pyenv
  apt:
    name: 
    - build-essential 
    - libssl-dev
    - zlib1g-dev
    - libbz2-dev
    - libreadline-dev
    - libsqlite3-dev
    - wget
    - curl
    - llvm
    - libncurses5-dev
    - libncursesw5-dev
    - xz-utils
    - tk-dev
    - libffi-dev
    - liblzma-dev
    - python-openssl
    - git
    state: latest
  become: yes

