- name: Install the spotify flatpak
  community.general.flatpak:
    name:  https://dl.flathub.org/repo/appstream/com.spotify.Client.flatpakref
    state: present
    method: user

- name: Install Goenv
  git:
    repo: https://github.com/syndbg/goenv.git
    dest: "{{ ansible_user_dir }}/{{ ansible_user_id }}/.goenv"
    